In [1]:
import torch

In [2]:
def sigmoid(x):
    return(1/(1+torch.exp(-x)))
    

In [8]:
features = torch.randn((1,5))
weights = torch.rand_like(features)
bias = torch.randn((1,1))

In [9]:
print(features)
print(weights)
print(bias)


tensor([[-0.0796,  1.1572,  0.6462,  1.4173, -0.0379]])
tensor([[0.3097, 0.7038, 0.4586, 0.6054, 0.5385]])
tensor([[1.1993]])


In [12]:
y = sigmoid(torch.mm(features,weigths.view(5,1))+bias)

tensor([[0.9544]])

In [13]:
features = torch.randn(1,3)
n_input = features.shape[1]
n_hidden = 2
n_output = 1


In [14]:
w1 = torch.randn(n_input,n_hidden)
w2 = torch.randn(n_hidden,n_output)

In [17]:
b1 = torch.randn(1,n_hidden)
b2 = torch.randn(1,n_output)

In [20]:
h = sigmoid(torch.mm(features, w1)+b1)

In [22]:
output = sigmoid(torch.mm(h,w2)+b2)

In [23]:
output

tensor([[0.4045]])

### Numpy and torch

In [25]:
import numpy as np
a = np.random.rand(4,3)

In [26]:
a

array([[0.56682956, 0.04045233, 0.22212374],
       [0.74396629, 0.00107941, 0.68654728],
       [0.14765427, 0.64189984, 0.47816536],
       [0.10486073, 0.31287389, 0.01880605]])

In [27]:
b = torch.from_numpy(a)

In [30]:
b

tensor([[0.5668, 0.0405, 0.2221],
        [0.7440, 0.0011, 0.6865],
        [0.1477, 0.6419, 0.4782],
        [0.1049, 0.3129, 0.0188]], dtype=torch.float64)

In [32]:
b.numpy()

array([[0.56682956, 0.04045233, 0.22212374],
       [0.74396629, 0.00107941, 0.68654728],
       [0.14765427, 0.64189984, 0.47816536],
       [0.10486073, 0.31287389, 0.01880605]])